#!/system/bin/sh

# Script that runs when *.shar shell archive is extraced
# Version 1.3, Copyright 2012 by Sven-Ola, License: GPLv3

case ${0%/*} in ${0}) DIR=${PWD};;*) case ${0} in /*) DIR=${0%/*};;*) DIR=${PWD}/${0%/*};DIR=${DIR%%/.};;esac;;esac

# Note: on i386, qemu may execute armel code as well. Reason to query i386 fist here.
CPU=$(${DIR}/i386/busybox ash -c "echo i386" 2>&- || ${DIR}/armel/busybox ash -c "echo armel" 2>&-)
case ${CPU} in "") echo "Unsupported CPU or architecture." >&2 && exit 1;;esac
${DIR}/${CPU}/busybox ash -c "test /proc/$$/exe -ef ${DIR}/${CPU}/busybox" || exec ${DIR}/${CPU}/busybox ash -- "${0}" "$@"
# Our busybox shell from here on

# Read some critical locations from bootdeb script
eval IMG=$(sed -n 's/^[[:space:]]*IMG[[:space:]]*=//p' ${DIR}/bootdeb|sed -n '$p')
eval MNT=$(sed -n 's/^[[:space:]]*MNT[[:space:]]*=//p' ${DIR}/bootdeb|sed -n '$p')

source ${DIR}/functions

eval IMG=$(sed -n 's/^[[:space:]]*IMG[[:space:]]*=//p' ${DIR}/bootdeb|sed -n '$p')

exit_autorun() {
	echo "$* No autorun. You may run ${DIR}/mk-debian manually." >&2
	exit 1
}

case ${IMG} in uuid:*)
	exit_autorun "IMG=${IMG} points to partition."
;;esac

test -e ${IMG} && {
	exit_autorun "IMG=${IMG} already present."
}

case ${IMG} in ""|/dev/*|/proc/*|/run/*|/sys/*)
	exit_autorun "IMG=${IMG} fails plausibility check."
;;esac

FREE=$(get_free "${IMG%/*}")

cat >&2 << EOF
About to install to ${IMG}. ${FREE:+You have ${FREE} Mb left on ${IMG%/*}. }If you want another image location, run the ${DIR}/mk-debian script manually.

To install now, enter a digit and a char:

0: 512 Mb, minimal setup e.g. OpenSSL server
1: 1024 Mb, medium setup e.g. LXDE desktop
2: 2047 Mb,  large setup e.g. office, browser
s: Debian Squeeze (2011, default, stable)
l: Ubuntu Lucid (2010, tested LTS version)
p: Ubuntu Precise (2012, untested LTS version)

Press [enter] without any input to abort.

EOF

DISTRO=
LOOPSIZE=
while [ -z "${DISTRO}" ] || [ -z "${LOOPSIZE}" ];do
	echo -n "Enter option (e.g. '0s' for 512 Mb Squeeze): "
	read n

	case ${n} in ""|q|Q) exit 0;;esac

	case ${n} in *s)
		DISTRO=squeeze
	;;*l)
		DISTRO=lucid
	;;*p)
		DISTRO=precise
	;;*)
		DISTRO=
	;;esac

	case ${n} in 0*)
		LOOPSIZE=512
	;;1*)
		LOOPSIZE=1024
	;;2*)
		LOOPSIZE=2047
	;;*)
		LOOPSIZE=
	;;esac

	if [ -z "${DISTRO}" ] || [ -z "${LOOPSIZE}" ];then
		echo "Enter TWO characters!" >&2
	fi
done

if ash -- ${DIR}/mk-debian -d ${DISTRO} ${LOOPSIZE};then
	ash -- ${DIR}/bootdeb stage2 && ash -- ${DIR}/cleanup
	echo >&2
	echo "Your next steps: enter '$(if [ -x ${ANDROID_ROOT:-/system}/bin/deb ];then echo deb;else echo ${DIR}/bootdeb;fi)' to start, 'apt-get update' to fetch package lists, and 'apt-get install andromize' to add a small packet that further adapts Debian to the Android environment." >&2
fi
