#!/bin/sh

# Clumsy replacement for upstart's /sbin/initctl, currently only
# tested for the ssh daemon. For a better replacement check out
# http://gyp.blogs.balabit.com/2011/01/using-upstart-in-a-chroot/
#
# Version 1.3, Copyright 2012 by Sven-Ola, License: GPLv3

CONF=/etc/init
PIDS=/var/run/upstart-
START_STOP_DAEMON=/sbin/start-stop-daemon

##### Functions #####

parse_config() {
	if [ -z "${1}" ];then
		echo "Missing job name" >&2
		exit 1
	fi
	if [ ! -f "${CONF}/${1}.conf" ];then
		echo "Unknown job: ${1}" >&2
		exit 1 
	fi
	IFS=
	eval $(sed -n '
s/^[[:space:]]\+//
s/[[:space:]]\+$//
s/#.*//
/^$/d
/^\(exec\|pre-start\|post-start\|pre-stop\|post-stop\)[[:space:]]\+script$/,/^end[[:space:]]\+script$/{
	s/^\([^[:space:]\-]\+\)-\([^[:space:]\-]\+\)/\1_\2/
	s/^end[[:space:]]\+script$/}/
	s/^\([^[:space:]]\+\)[[:space:]]\+script$/\1(){/
	p
	d
}
/^\(exec\|pre-start\|post-start\|pre-stop\|post-stop\)[[:space:]]\+/{
	s/^\([^[:space:]\-]\+\)-\([^[:space:]\-]\+\)/\1_\2/
	s/\([^[:space:]]\+\)[[:space:]]\+\(.*\)/\1="\2"/
	p
	d
}
/^\(description\)[[:space:]]\+/{
	s/\([^[:space:]]\+\)[[:space:]]\+/\1=/
	p
	d
}
' "${CONF}/${1}.conf")
	unset IFS
}

usage() {
	cat<<EOF
Usage:
  ${0##*/} [Options] $(case ${0##*/} in initctl)echo "(start|stop|restart) ";;esac)[job name]

Options:
  -h	display usage text and settings
EOF
	exit ${1}
}

pre_start() { return 0;}
post_start() { return 0;}
pre_stop() { return 0;}
post_stop() { return 0;}

##### Main #####

while getopts "h" opt;do
	case ${opt} in h)
		usage 0
	;;*)
		usage 1
	;;esac
done

shift $(( ${OPTIND} - 1 ))

cmd=${0##*/}
case ${cmd} in initctl)
	cmd=${1}
	case ${cmd} in "")
		usage 1
	;;esac
	shift
;;esac

case ${cmd} in start)
	parse_config "${1}"
	echo "Starting ${description}..."
	case ${exec} in "")
		echo "No exec in ${CONF}/${1}.conf" >&2
		exit 1
	;;esac
	case ${pre_start} in "")
		pre_start
	;;*)
		eval ${pre_start}
	;;esac
	${START_STOP_DAEMON} --start --pidfile ${PIDS}${1}.pid --make-pidfile --background --exec ${exec%% *} -- ${exec#* }
	case ${post_start} in "")
		post_start
	;;*)
		eval ${post_start}
	;;esac
;;stop)
	parse_config "${1}"
	echo "Stopping ${description}..."
	case ${exec} in "")
		echo "No exec in ${CONF}/${1}.conf" >&2
		exit 1
	;;esac
	case ${pre_stop} in "")
		pre_stop
	;;*)
		eval ${pre_stop}
	;;esac
	name=${exec%% *}
	${START_STOP_DAEMON} --stop --name ${name##*/} --pidfile ${PIDS}${1}.pid --retry 5
	case ${post_stop} in "")
		post_stop
	;;*)
		eval ${post_stop}
	;;esac
;;restart)
	${0%/*}/initctl stop ${1}
	${0%/*}/initctl start ${1}
;;*)
	echo "Unknown command: ${cmd}" >&2
	usage 1
esac

exit 0
